import pathlib,json,re,hashlib,subprocess
D=pathlib.Path('/agent/workspace/owl-native-prep/real-probe-final');P=D.parent
assert (D/'summary.json').exists(),'Probe not finished'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
subprocess.run(['python3',str(D/'analyze.py')],stdout=(D/'analysis.log').open('w'),stderr=subprocess.STDOUT,check=True)
(D/'final-processes.txt').write_text(subprocess.check_output(['ps','-eo','pid,ppid,rss,comm,args'],text=True))
before=json.loads((D/'source-binary-hashes-before.json').read_text());after={p:sha(pathlib.Path(p)) for p in before}
(D/'source-binary-preservation.json').write_text(json.dumps({'unchanged':before==after,'hashes_after':after,'differences':[p for p in before if before[p]!=after[p]]},indent=2))
stdout=(D/'stdout.log').read_text();stderr=(D/'stderr.log').read_text();summary=json.loads((D/'summary.json').read_text());scores=json.loads((D/'independent-scores.json').read_text());preservation=json.loads((D/'prior-evidence-preservation.json').read_text())
models=json.loads((D/'model-hash-reverification.json').read_text());pins=json.loads((D/'pinned-production-verification.json').read_text())
expected_errors={'stale-load-permit':'Stale load permit','stale-queued-permit':'Stale request permit','output-truncation':'Output token limit reached without EOS'}
for field in ['text','system']:
 expected_errors['unpaired-surrogate-'+field]='Malformed UTF-16 input'
 for image in ['false','true']:expected_errors[f'invalid-C328-{field}-image-{image}']='Malformed UTF-8 input'
checks={name:(D/(name+'.error.txt')).exists() and text in (D/(name+'.error.txt')).read_text() for name,text in expected_errors.items()}
for name,expected in [('text-sanity','4'),('red-image-sanity','Red'),('unicode-positive','4'),('reload-text-sanity','4')]:checks[name]=(D/(name+'.output.txt')).exists() and (D/(name+'.output.txt')).read_text()==expected
for k in ['A','B']:checks['gui-'+k]=scores[k].get('production_codec_accepted',False) and scores[k].get('point_inside_search_bbox',False)
checks['close-acks']=all(k+'=true' in stdout for k in ['PRE_RELOAD_NATIVE_CLOSE_ACK','FINAL_NATIVE_CLOSE_ACK','SECOND_CLOSE_ACK'])
checks['normal-exit']=summary['exit_code']==0 and summary['termination']=='NORMAL_PROCESS_EXIT'
checks['source-binary-unchanged']=before==after;checks['historical-evidence-unchanged']=preservation['unchanged']
checks['actual-pinned-JNI-mapped']=str(D/'pinned-host/libunoone_owl.so') in (D/'loaded-process-maps.txt').read_text()
(D/'assertions.json').write_text(json.dumps(checks,indent=2))
rows=[]
for match in re.finditer(r'^PROBE (\d+) (SUCCESS|ERROR) ([^ ]+) elapsedMs=(\d+) (.*)$',stdout,re.M):
 timestamp,state,name,ms,message=match.groups();path=D/(name+('.output.txt' if state=='SUCCESS' else '.error.txt'));rows.append({'timestampMs':int(timestamp),'outcome':state,'name':name,'elapsedMs':int(ms),'headline':message,'raw_file':path.name})
(D/'all-outcomes.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
receipt=re.search(r'CONFIG (.*)',stdout).group(1)
report=['# Final real Owl probe after load-permit + stack-batch repairs','', '**SYNTHETIC HOST TEST — NOT ANDROID / NOT PHONE QUALIFICATION.**','', '## Result', '', ('PASS: all requested probe assertions passed.' if all(checks.values()) else 'INCOMPLETE/FAIL: see exact failed assertions below.')+' One run, no retries, no output repair or cherry-picking. All raw returns and exceptions retained. No actions dispatched.', '',f'Evidence: `{D}/`. Sole model JVM exited: `{summary["termination"]}`, exit `{summary["exit_code"]}`, wall `{summary["elapsed_seconds"]:.3f}s`. Resource-exclusive preflight, inference and final process snapshots retained. No Gradle, production edits, native compiler, downloads or commits. Standalone harness Kotlin compilation finished before model launch.', '', '## Identity and actual defaults','',f'```\n{receipt}\n```','', 'Called `load(modelRoot)` without budget overrides; GUI requests reserve all 256 output tokens. CPU2; actual ctx2048/output256/imageEdge512. Unchanged 256×256 synthetic fixtures are below max edge512 and tokenize to64 image tokens, not256. Actual production OwlPromptBuilder and OwlOutputCodec sources compiled into harness; actual repaired runtime/planner classes pinned without replacements. JNI loaded from own pinned copy, confirmed by `/proc/self/maps`; dependencies and sources hashed before/after.', '', 'Repaired production source binary origin: `/agent/workspace/owl-native-prep/race-production-host`. SHA pins asserted before launch and copied into `pinned-host/`:','']
for p,h in pins['expected_and_verified'].items():report.append(f'- `{p}`: `{h}`')
report+=['','Existing real 4B decoder and mmproj freshly streamed/hash verified; no redownload:']
for m in models:report.append(f'- `{pathlib.Path(m["path"]).name}`: {m["bytes"]} bytes, SHA256 `{m["sha256"]}`.')
report+=['','Full source/class/dependency SHA256 manifest: `source-binary-hashes-before.json`; unchanged verification: `source-binary-preservation.json`. Exact argv, libraries, no-AS-limit receipt: `invocation.json`.','', '## Both moved-Search GUI outcomes','', 'Exact builder inputs: `Click the Search button.` / `Synthetic test fixture only; no real device or execution.` Exact expanded prompts: `official-system.txt` and `official-user.txt`. Bounds never supplied to inference. Images copied byte-for-byte from previous default probe and visually inspected: A Search lower-right, B Search upper-left; Home swapped; Settings unchanged.','']
for k in ['A','B']:
 s=scores[k];report+=[f'### Fixture {k}', '',f'Production codec accepted: **{s.get("production_codec_accepted")}**; point `{s.get("point")}`; independent normalized Search bbox `{s["search_bbox_normalized"]}`; inside **{s.get("point_inside_search_bbox")}**.', '', 'Exact raw model return (no repair):', '```',s.get('exact_raw_model_output','NO OUTPUT; see raw error'),'```','']
report+=['## Every test outcome','', '| Test | Return / exception | Wall ms |','|---|---|---|']
for r in rows:report.append(f'| {r["name"]} | {r["outcome"]}: {r["headline"].replace("|","/")} | {r["elapsedMs"]} |')
report+=['','Full raw strings / stack traces are separate `.output.txt` / `.error.txt`; `all-outcomes.json` indexes all results. Harness exit0 alone is not a claim every operation succeeded. Negative cases are expected rejections.', '', 'Malformed raw C328 system/text, with/without image, and Kotlin unpaired UTF-16 were all tested **before first generation**. Stale load permit checked before the actual default load; stale queued generate permit checked before GUI calls. Truncation returns no partial proposal. Reload is sequential, allowed only after positive close ACK and <380s elapsed; one new default load and one text check, then final/repeated close. This is ordinary public close/reload, not an exhaustive concurrent load-race test.','', '### Active cancellation and close event receipts','```']
report += [line for line in stdout.splitlines() if any(x in line for x in ['ACTIVE_','CLOSE_ACK','RELOAD_SKIPPED'])]
report+=['```', 'Active-cancel timing is host wall around public generate/JNI, not an internal native profiler. Prefill cancellation returning generic `Vision/prefill failed` remains a diagnostic classification limitation, not an accepted partial output. No decode-stage or vision-stage cancellation qualification asserted.','', '## Native admission and resource monitor','```']
report += [line for line in stderr.splitlines() if 'Owl admission:' in line]
report+=['```', '', 'External monitor every100ms. Child RSS or retained VmHWM ≥3.8GiB (3,984,588KiB), or system MemAvailable <256MiB, triggers RESOURCE_LIMIT; only own child PID TERM then KILL after3s. External wall bound470s (<8min, plus at most3s termination grace). No RLIMIT_AS; invocation records [-1,-1]. No limit signals required if normal exit. Whole-cgroup memory recorded separately, never confused with child RSS.','', f'- Child wall: {summary["elapsed_seconds"]:.3f}s; peak sampled RSS {summary["peak_RSS_KiB"]}KiB ({summary["peak_RSS_KiB"]/1048576:.6f}GiB).',f'- Peak VmHWM {summary["peak_VmHWM_KiB"]}KiB; minimum MemAvailable {summary["min_MemAvailable_KiB"]}KiB.',f'- Peak whole-cgroup memory.current {summary["peak_memory_current_bytes"]} bytes.', '- Sampling cannot rule out sub100ms transients; VmHWM retains observed child high-water mark. Cached/mmap host startup is not cold phone startup.', '', '## Preservation, assertions, limits', '',f'Historical `/real-probe` and `/real-probe-default` evidence unchanged: **{preservation["unchanged"]}**, {preservation["file_count_before"]} files. No old evidence overwritten. Source/pinned binaries/dependencies unchanged: **{before==after}**.', '', '```json', json.dumps(checks,indent=2),'```', '', 'This narrowly revalidates real host inference with the repaired production JNI and Kotlin. It does NOT establish Android ABI/loading/install, real screenshot/touch dispatch, broad grounding accuracy, phone memory/thermal/latency, race exhaustiveness or safety across all upstream allocation failures. Production code not edited. Other workers may resume resource-heavy work after this handoff.']
pathlib.Path('/agent/workspace/owl-final-probe-handoff.md').write_text('\n'.join(report)+'\n')
(D/'evidence-manifest.sha256.json').write_text(json.dumps({str(p.relative_to(D)):sha(p) for p in D.rglob('*') if p.is_file() and p.name!='evidence-manifest.sha256.json'},indent=2))
print(json.dumps({'summary':summary,'checks':checks},indent=2))
