import pathlib,json,re,hashlib,subprocess,math
D=pathlib.Path('/agent/workspace/owl-native-prep/voice-prompt-v2');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
stdout=(D/'stdout.log').read_text();stderr=(D/'stderr.log').read_text();fixtures={f['id']:f for f in json.loads((D/'fixtures.json').read_text())};summary=json.loads((D/'summary.json').read_text())
admissions=[dict(zip(['text_tokens','text_plus_vision','image_tokens','reserved_output','context','image_edge'],map(int,x))) for x in re.findall(r'Owl admission: text_tokens=(\d+) text_plus_vision=(\d+) image_tokens=(\d+) reserved_output=(\d+) context=(\d+) image_edge=(\d+)',stderr)]
order=[('baseline','N1'),('candidate','N1'),('candidate','N2'),('baseline','N2'),('baseline','F1'),('candidate','F1'),('candidate','W1'),('baseline','W1')]
rows=[]
for i,(v,cid) in enumerate(order):
 name=v+'-'+cid;f=fixtures[cid];m=re.search(r'GENERATE_(OK|ERROR) '+name+r' elapsedMs=(\d+)',stdout);p=D/(name+'.codec.json');codec=json.loads(p.read_text()) if p.exists() else None
 native=D/(name+'.native.txt');nt=native.read_text() if native.exists() else '';raw=D/(name+'.output.txt');errors=[(D/(name+s)).read_text() for s in ['.codec-error.txt','.error.txt'] if (D/(name+s)).exists()]
 xy=[codec['x'],codec['y']] if codec and codec['action']=='click' else None
 b=f['bbox'];pixel=[math.floor(n*256/1000) for n in xy] if xy else None
 bbox=bool(pixel and b[0]<=pixel[0]<b[2] and b[1]<=pixel[1]<b[3]) if f['operation']!='WRITE' and codec else None
 exact_text=(codec['text']==f['value']) if codec and f['operation']=='WRITE' else None
 correct=bool(codec and codec['action']==('type' if f['operation']=='WRITE' else 'click') and (exact_text if f['operation']=='WRITE' else bbox) and 'exact_native_action_match=true' in nt)
 rows.append(dict(order=i+1,variant=v,case=cid,operation=f['operation'],label=f['label'],status=m[1] if m else 'NOT_COMPLETED',wall_ms=int(m[2]) if m else None,admission=admissions[i] if i<len(admissions) else None,production_codec_accepted=bool(codec),decoded=codec,pixel=pixel,bbox_hit=bbox,exact_text_match=exact_text,native_action_match='exact_native_action_match=true' in nt,valid_correct=correct,raw_output=raw.read_text() if raw.exists() else None,native_result=nt,errors=errors,generated_token_count=None,native_phase_timings=None))
(D/'results.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2));(D/'native-admission-profile.txt').write_text('\n'.join(x for x in stderr.splitlines() if 'Owl admission' in x or 'Owl load' in x))
before=json.loads((D/'source-binary-hashes-before.json').read_text());changed=[p for p,h in before.items() if sha(pathlib.Path(p))!=h]
(D/'source-binary-preservation.json').write_text(json.dumps(dict(all_unchanged=not changed,checked_files=len(before),changed=changed),indent=2));(D/'final-processes.txt').write_text(subprocess.check_output(['ps','-eo','pid,ppid,rss,comm,args'],text=True))
base=[r for r in rows if r['variant']=='baseline'];cand=[r for r in rows if r['variant']=='candidate'];allcorrect=all(r['valid_correct'] for r in rows)
b=sum(r['wall_ms'] or 0 for r in base)/4;c=sum(r['wall_ms'] or 0 for r in cand)/4
lines=['# SwiftV2Probe — held-out synthetic real 4B JNI validation','', '**CANDIDATE ONLY. FULL remains default. No phone-speed or general noninferiority claim.**','',f'Archive: `{D}`','', '## Declared workflow and frozen design','Four NEW 256×256 GUI cases: navigation CLICK Library, navigation CLICK Settings at new positions, FOCUS Search query, and WRITE an already-focused Draft title with exact literal `AbC 42`. Safe NAVIGATION controls were used instead of semantically unknown/protected Continue. Fixtures and independent renderer bounding boxes were frozen before inference; no expected coordinates or native target geometry were passed to either model prompt. The WRITE literal value was supplied identically as required task data. All screens visibly marked SYNTHETIC GUI / TEST. They are not real screenshots. W1 title and field label slightly overlap; field, caret and focused marker remain visible. This fixed fixture was not repaired or replaced after observing outputs.','', 'Actual unchanged production OwlPromptBuilder.build versus actual compiled buildScopedV2 / COMPACT_CANDIDATE_V2. Identical per-case native-goal JSON and PNG bytes; baseline wraps same goal via build(scopedGoal, empty untrustedData), candidate uses same data directly. Exact system/user prompts and source archived. Order: baseline/candidate N1; candidate/baseline N2; baseline/candidate F1; candidate/baseline W1. Exactly eight attempted calls, no retries/tuning/cherry-picking/output repairs and no malformed-output coordinate extraction.','', 'Existing production runtime classes, JNI and llama shared libraries verified against prior voice-prompt-ab hashes (candidate source intentionally V2, V1 archived unchanged). Decoder Q4_K_M and mmproj Q8_0 freshly SHA-256 verified against receipts. One JVM/model, sequential native greedy requests, default ctx2048/output256/imageEdge512 CPU2. Native request memory reset remains production behavior. No Gradle, model downloads, production/default/native edits or address-space limit. Standalone Kotlin compilation finished before model load.','', '## Results','| Order | Variant/case | Wall ms | Native text / image tokens | Codec | Bbox or exact text | Native exact action | Valid + correct |','|---|---|---:|---|---|---|---|---|']
for r in rows:
 a=r['admission'] or {};q=r['exact_text_match'] if r['operation']=='WRITE' else r['bbox_hit'];lines.append(f"| {r['order']} | {r['variant']}-{r['case']} | {r['wall_ms']} | {a.get('text_tokens')} / {a.get('image_tokens')} | {r['production_codec_accepted']} | {q} | {r['native_action_match']} | {r['valid_correct']} |")
lines+=['',f"Production-codec valid/correct: baseline {sum(r['valid_correct'] for r in base)}/4, V2 {sum(r['valid_correct'] for r in cand)}/4.",'']
for r in rows:
 if not r['valid_correct']:
  lines += [f"Failure retained: {r['variant']}-{r['case']}: " + ('; '.join(e.splitlines()[0] for e in r['errors']) or 'Wrong native action/text/target or no completed result') + '. No malformed coordinates extracted or rescued.']
if allcorrect:lines+=[f'All eight returns were valid/correct on this sample. Four-case mean total JNI generate wall: baseline {b:.1f}ms, V2 {c:.1f}ms ({(1-c/b)*100:.1f}% lower). This describes only these four synthetic cases; it does not establish general accuracy, noninferiority or phone speed.']
else:lines+=[f'Observed raw mean return walls: baseline {b:.1f}ms, V2 {c:.1f}ms. Do NOT interpret a faster invalid/incorrect return as successful-action speedup. No overall speedup claim is warranted when any case fails.']
lines+=['', 'Quality caveat: candidate-N2 binds at pixel x=128, exactly the native target left edge (left-inclusive bounds), not the requested center. It passes the frozen bbox/native-action criterion, but provides no robustness margin or center-grounding evidence. Invalid candidate-F1 coordinates are not scored (null), rather than treated as a repaired click.', '', 'Actual token counts are JNI admission text/image counts, not estimates. Generated-output token counts and stage/prefill/decode/TTFT counters are not exposed by unchanged runtime: recorded null, not fabricated. Measured walls cover public generate/JNI calls; model-load wall is separately in stdout.','', '## Production native checks and limits','Actual production OwlOutputCodec.decode executes first. Only accepted outputs enter coordinate/text scoring. Actual production OwlNativeBinding.translate is compiled from source; production DeviceActionValidator and device model dependencies are loaded from existing core classes whose hashes are archived. Each case uses synthetic native UiSnapshot, scope, receipt and clock, asserting expected ClickNode/FocusNode/SetText (exact case-sensitive `AbC 42`). A focus click is not counted as WRITE; no write is counted without a focused field. These simulated native contracts test code paths, NOT real capture consent, freshness, ownership, authorization, dispatch or device success. No UI action was dispatched. Non-ASCII character preservation is not established by the permitted ASCII-valued Unicode literal `AbC 42`.','', '## Resource receipt','```json',json.dumps(summary,indent=2),'```','RSS/VmHWM ceiling3.8GiB; MemAvailable floor256MiB; 100ms monitoring; outer900s; native request180s. Child PID termination only if a guard trips. No RLIMIT_AS imposed. Preflight and process receipts archived.',f'Post-run preservation: {len(before)} files checked; changed={changed}.','', '## Recommendation','Keep FULL default and V2 disabled. Preserve rejected V1 and all its failures. At most these four synthetic paired cases support a narrowly scoped follow-up; no broad promotion or general noninferiority.','', '## Raw unmodified EOS outputs']
for r in rows:lines += ['',f"### {r['variant']}-{r['case']}",'```',r['raw_output'] or '\n'.join(r['errors']) or 'NO RETURN','```']
text='\n'.join(lines)+'\n';(D/'report.md').write_text(text);pathlib.Path('/agent/workspace/owl-prompt-v2-handoff.md').write_text(text)
(D/'evidence-manifest.sha256.json').write_text(json.dumps({str(p.relative_to(D)):sha(p) for p in D.rglob('*') if p.is_file() and p.name!='evidence-manifest.sha256.json'},indent=2))
print(json.dumps(dict(baseline_correct=sum(r['valid_correct'] for r in base),candidate_correct=sum(r['valid_correct'] for r in cand),baseline_mean_ms=b,candidate_mean_ms=c,all_valid_correct=allcorrect,summary=summary,source_files_changed=changed),indent=2))
