import pathlib,json,re,hashlib,subprocess
D=pathlib.Path('/agent/workspace/owl-native-prep/voice-prompt-ab')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
stdout=(D/'stdout.log').read_text();stderr=(D/'stderr.log').read_text();fixture=json.loads((D/'fixture.json').read_text());summary=json.loads((D/'summary.json').read_text())
admissions=[dict(zip(['text_tokens','text_plus_vision','image_tokens','reserved_output','context','image_edge'],map(int,x))) for x in re.findall(r'Owl admission: text_tokens=(\d+) text_plus_vision=(\d+) image_tokens=(\d+) reserved_output=(\d+) context=(\d+) image_edge=(\d+)',stderr)]
rows=[]
for i,(variant,case) in enumerate([('baseline','A'),('candidate','B'),('candidate','A'),('baseline','B')]):
 name=f'{variant}-{case}';m=re.search(r'GENERATE_(OK|ERROR) '+name+r' elapsedMs=(\d+)',stdout);codec=(D/(name+'.codec.txt'));c=codec.read_text() if codec.exists() else '';point=re.search(r'action=click;x=([\d.]+);y=([\d.]+);',c);xy=list(map(float,point.groups())) if point else None;box=fixture[case]['search_bbox_normalized'];hit=bool(xy and box[0]<=xy[0]<=box[2] and box[1]<=xy[1]<=box[3]);raw=D/(name+'.output.txt');err=D/(name+'.error.txt')
 rows.append({'order':i+1,'variant':variant,'case':case,'generate_status':m[1] if m else 'NOT_COMPLETED','total_generate_wall_ms':int(m[2]) if m else None,'admission':admissions[i] if i<len(admissions) else None,'EOS_return':bool(m and m[1]=='OK'),'raw_output':raw.read_text() if raw.exists() else None,'generation_error':err.read_text() if err.exists() else None,'production_codec_accepted':codec.exists(),'codec':c,'coordinate':xy,'search_bbox':box,'inside_search':hit,'output_token_count':None,'native_phase_timings':None})
for r in rows:
 raw_match=re.search(r'"coordinate"\s*:\s*\[\s*([\d.]+)\s*,\s*([\d.]+)\s*\]',r['raw_output'] or '')
 diagnostic=list(map(float,raw_match.groups())) if raw_match else None;box=r['search_bbox']
 r['raw_diagnostic_coordinate']=diagnostic;r['raw_diagnostic_bbox_hit']=bool(diagnostic and box[0]<=diagnostic[0]<=box[2] and box[1]<=diagnostic[1]<=box[3]);r['raw_diagnostic_not_codec_validated']=True
(D/'results.json').write_text(json.dumps(rows,indent=2));(D/'native-admission-profile.txt').write_text('\n'.join(x for x in stderr.splitlines() if any(s in x.lower() for s in ['owl admission','eval time','encode time','total time','tokens per second'])))
before=json.loads((D/'source-binary-hashes-before.json').read_text());changed=[p for p,h in before.items() if sha(pathlib.Path(p))!=h];assert not changed,changed
(D/'source-binary-preservation.json').write_text(json.dumps({'all_unchanged':True,'checked_files':len(before)},indent=2));(D/'final-processes.txt').write_text(subprocess.check_output(['ps','-eo','pid,ppid,rss,comm,args'],text=True))
base=[r for r in rows if r['variant']=='baseline'];cand=[r for r in rows if r['variant']=='candidate'];b=sum(r['total_generate_wall_ms'] or 0 for r in base)/2;c=sum(r['total_generate_wall_ms'] or 0 for r in cand)/2
lines=['# Owl full vs scoped candidate: real host A/B','', '**SYNTHETIC HOST TEST ONLY — TWO CASES, NOT PHONE SPEED OR NONINFERIORITY.**','',f"Archive: `{D}`",'', '## Design and identity','Actual unchanged production OwlPromptBuilder.build versus actual compiled buildScoped COMPACT_CANDIDATE_V1; no app integration, production edits, downloads, Gradle, or native changes. Standalone compiler exited before model was loaded. One model/JVM, sequential order baseline-A, candidate-B, candidate-A, baseline-B, no retry/tuning/output repair. Existing production runtime and JNI verified against real-probe-final hashes before launch and after run. Existing 4B Q4_K_M decoder plus Q8_0 mmproj freshly hash verified. Runtime defaults ctx2048/output256/imageEdge512, CPU2, greedy; unchanged 256x256 PNGs and actual image token admission preserved.','', 'Both variants receive identical goal metadata: `{"operation":"CLICK","exactLabel":"Search","scopePackage":"example.app"}`. Baseline passes this exact JSON as scopedGoal, empty untrustedData; candidate obtains it directly from buildScoped. No bbox or case identity supplied to inference. This differs from earlier historical probe wording; only the paired results here are compared. Package is synthetic metadata, not Android scope proof.','', 'Production JNI clears model memory before every accepted generation (owl_jni.cpp line86), then greedy sampling line87; no retained-request context. Success returns only at EOG; truncation/error outputs are not promoted. Full supplied system/user prompts, candidate source/version/SHA, invocation, model hash receipts, raw outputs, production codec outputs, PNGs, independent bbox scores, stderr native admission/profile and 100ms RSS samples are archived.','', '## Results','| Order | Variant/case | Generate wall ms | Text / image tokens | Codec | Search hit |','|---|---|---:|---|---|---|']
for r in rows:
 a=r['admission'] or {};lines.append(f"| {r['order']} | {r['variant']}-{r['case']} | {r['total_generate_wall_ms']} | {a.get('text_tokens')} / {a.get('image_tokens')} | {r['production_codec_accepted']} | {r['inside_search']} |")
lines += ['',f'Observed two-case mean total generate wall: baseline {b:.1f}ms, candidate {c:.1f}ms; {(1-c/b)*100:.1f}% lower candidate mean.' if b else 'No complete timing comparison.', '', 'Native stage counters are not exposed by this runtime. These are measured public generate/JNI total wall times and native admission token counts, NOT inferred prefill, vision, decode or time-to-first-token measurements. Output generated-token count is not exposed; null in results, not estimated. Any library diagnostic timing lines remain raw evidence, not a phase profiler.', '', '## Resources and completion', '```json',json.dumps(summary,indent=2),'```','Native max request180s, outer900s; RSS3.8GiB / MemAvailable256MiB guards target child PID only. No AS limit imposed. Preflight and final processes retained.', '', '## Recommendation','Keep FULL as default; do not enable this candidate. Candidate failed the production codec on both cases, so its shorter return time is NOT successful-action latency or a usable speedup. Both exact failures remain archived; no tuning/retry/output repair was performed. These two synthetic clicks cannot establish general accuracy, noninferiority, phone speed, or authorization safety.', '', '## Raw coordinate diagnostic','Candidate raw text contains coordinates inside the correct Search bounds in both cases, but its literal `<tool_call> JSON </tool_call>: ...` omits the required mobile_use envelope and places JSON outside the tool_call block. Both outputs are rejected by the actual production codec. Raw coordinate extraction is diagnostic only, not output repair, validation, dispatch or successful-action evidence; detailed raw and codec scores are separate in results.json.', '', '## Raw EOS outputs']
for r in rows:lines += ['',f"### {r['variant']}-{r['case']}",'```',r['raw_output'] or r['generation_error'] or 'NO RETURN','```']
text='\n'.join(lines)+'\n';(D/'report.md').write_text(text);pathlib.Path('/agent/workspace/owl-prompt-ab-handoff.md').write_text(text)
(D/'evidence-manifest.sha256.json').write_text(json.dumps({str(p.relative_to(D)):sha(p) for p in D.rglob('*') if p.is_file() and p.name!='evidence-manifest.sha256.json'},indent=2))
print(json.dumps({'results':rows,'summary':summary,'baseline_mean_ms':b,'candidate_mean_ms':c},indent=2))
